
<?php
/**
 * Route table. Generated by `/data/wwwroot/paste/generator.php` at 2020-03-15 09:27:47.
 * YOU DON'T HAVE TO MODIFY THIS FILE, JUST GENERATE IT :)
 */

$apiPost = new \App\Api\Post();
Flight::route('POST /post', array($apiPost, 'create'));
Flight::route('GET /post/@id', array($apiPost, 'get'));

$apiWelcome = new \App\Api\Welcome();
Flight::route('GET /', array($apiWelcome, 'index'));

